# This is a basic workflow to help you get started with Actions

name: Deploy Ninjago QA

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags: [ ninjago-qa ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Deploy"
  working-directory: packages/ninjago
  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Builds the app
    - name: Build
      run: echo Building Ninjago!

    # Deploys the app
    - name: Deploy
      run: echo Deploying Ninjago to QA!!
