# This is a basic workflow to help you get started with Actions

name: Selector

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: pull_request
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Selector"
  Selector:
    runs-on: ubuntu-latest
    container: bitnami/git:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install git
      run: sudo apt-get install -y git
    - name: Run selector
      run: bash selector.sh
