# This is a basic workflow to help you get started with Actions

name: Selector

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Selector"
  Selector:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: bitnami/git:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_TOKEN }}

    - name: Run selector
      run: bash selector.sh
